context("Smoke")


test_that("@tests captures tests", {
  out <- roxygen2::roc_proc_text(roxytest::testthat_roclet(), "
    #' @tests 
    #' expect_equal(2, 2)
    #'
    NULL", registry = roclet_tags.roclet_testthat())[[1]]
  
  # # Generated by roxytest: Do not edit by hand!
  # 
  # context("File R/file2e6038670aaf")
  # 
  # test_that("Function ()", {
  #   a <- 2
  # })
  
  expect_match(out, "^# Generated by roxytest: Do not edit by hand!")
  expect_match(out, 'context\\("File R/.*"\\)')
  expect_match(out, 'test_that\\("Function \\(\\)", \\{\\s*expect_equal\\(2, 2\\)\\s*\\}\\)')
})
