context("testthat roclet")


test_that("@tests captures tests", {
  out <- roxygen2::roc_proc_text(testthat_roclet(), "
    #' @tests 
    #' expect_equal(2, 2)
    #'
    NULL")
  out <- out[[1]]
  
  # # Generated by roxytest: Do not edit by hand!
  #
  # context("<text>")
  #  
  # test_that("[unknown alias] @ L5", {
  #  expect_equal(2, 2)
  # })
  
  expect_match(out, "^# Generated by roxytest: Do not edit by hand!")
  expect_match(out, 'context("<text>")', fixed = TRUE)
  expect_match(out, 'test_that(\"[unknown alias] @ L5\", {\n  expect_equal(2, 2)\n})', fixed = TRUE)
})

test_that("All good", {
  out <- roxygen2::roc_proc_text(testthat_roclet(), "
    #' Summing two numbers
    #'
    #' @param x A number
    #' @param y Another number
    #' 
    #' @tests 
    #' expect_equal(f(0, 0), 0)
    #' expect_equal(f(2, 3), 5)
    f <- function(x, y) {
      x + y
    }")
  out <- out[[1]]
  
  expect_match(out, "^# Generated by roxytest: Do not edit by hand!")
  expect_match(out, 'context("<text>")', fixed = TRUE)
  expect_match(out, 'test_that(\"Function f() @ L10\", {\n  expect_equal(f(0, 0), 0)\n  expect_equal(f(2, 3), 5)\n})', fixed = TRUE)
})

test_that("No @tests is ignoted", {
  out <- roxygen2::roc_proc_text(testthat_roclet(), "
    #' Summing two numbers
    #'
    #' @param x A number
    #' @param y Another number
    f <- function(x, y) {
      x + y
    }")
  expect_equal(out, list())
  
  output <- roxygen2::roclet_output(testthat_roclet(), out, base_path = NULL)
  expect_equal(output, NULL)
})



test_that("Multiple functions", {
  out <- roxygen2::roc_proc_text(testthat_roclet(), "
                                 #' A function to do x
#' 
#' @param x A number
#' 
#' @tests 
#' expect_equal(foo(2), sqrt(2))
#' expect_error(foo(\"a string\"))
#' 
#' @return something
foo <- function(x) {
  return(sqrt(x))
}

#' A function to do y
#' 
#' @param x Character vector
#' @param y Character vector
#' 
#' @tests 
#' expect_equal(bar(\"A\", \"B\"), paste(\"A\", \"B\", sep = \"/\"))
#' 
#' @export
bar <- function(x, y) {
  paste0(x, \"/\", y)
}

#' A function with missing parameter docs
#' 
#' @param x Character vector
#' 
#' @export
foobar <- function(x, y) {
  paste0(x, \"/\", y)
}
")
  expect_equal(length(out), 1)
  out <- out[[1]]
  
  expect_match(out, "^# Generated by roxytest: Do not edit by hand!")
  expect_match(out, 'Function foo() @', fixed = TRUE)
  expect_match(out, 'Function bar() @', fixed = TRUE)
  expect_false(grepl('Function foobar() @', out, fixed = TRUE))
})

