# Adapted from roxygen2's
# https://github.com/klutometis/roxygen/blob/master/R/rd.R

#' Roclet: make testthat test-files.
#'
#' @family roclets
#' @description This roclet is the workhorse of roxytest, 
#' producing the testthat test files specified.
#' 
#' Generally you will not call this function directly
#' but will instead use roxygenise() specifying the testthat roclet
#' 
#' @seealso Other roclets:
#' \code{\link[roxygen2]{namespace_roclet}}, 
#' \code{\link[roxygen2]{rd_roclet}},
#' \code{\link[roxygen2]{vignette_roclet}}.
#' 
#' @export
testthat_roclet <- function() {
  return(roxygen2::roclet("testthat"))
}


#' @export
roclet_tags.roclet_testthat <- function(x) {
  list(
    tests = tag_tests
  )
}

#' @export
roclet_process.roclet_testthat <- function(x,
                                     blocks,
                                     env,
                                     base_path,
                                     global_options = list()) {
  
  testfiles <- list()
  
  for (block in blocks) {
    testthat <- block_to_testthat(block, 
                                  base_path = base_path, 
                                  env = env, 
                                  global_options = global_options)

    if (is.null(testthat$filename) || is.null(testthat$test)) {
      next
    }
    
    
    testfiles[[testthat$filename]] <- c(testfiles[[testthat$filename]], 
                                        list(testthat))
  }
  
  return(testfiles)
}

block_to_testthat <- function(block, base_path, env, global_options = list()) {
  testthat_file <- list()
  
  test <- if (!is.null(block$test)) {
    test <- block$test
  } else {
    NULL
  }
  
  testthat_file$test <- test
  
  filename <- basename(attr(block, "filename"))
  testthat_file$filename <- filename
  
  testthat_file$functionname <- attr(block, "object")$alias

  return(testthat_file)
}

#' @export
roclet_output.roclet_testthat <- function(x, results, base_path, ..., is_first = FALSE) {
  verify_testthat_used()
  
  roclet_clean.roclet_testthat(x, base_path)
  
  testthat_path <- normalizePath(file.path(base_path, "tests", "testthat"))
  
  paths <- names(results)
  
  
  for (i in seq_along(results)) {
    path <- file.path(testthat_path, paste0("test-roxytest-", paths[i]))
    
    contents <- lapply(results[[i]], function(result) {
      test <- result$test
      test <- gsub("^\\s*(.*?)\\s*$", "\\1", test)
      test_indented <- paste0("  ", gsub("\n", "\n  ", test, fixed = TRUE))
      test_name <- paste0("Function ", 
                          roxygen2:::quote_if_needed(result$functionname), "()")

      paste0('test_that("', test_name, '", {', "\n", 
             test_indented, "\n",
             "})\n")
    })
    
    contents <- paste0(contents, collapse = "\n\n")
    
    path_quoted <- roxygen2:::quote_if_needed(paths[i])
    contents <- paste0("# Generated by roxytest: Do not edit by hand!\n\n", 
                       'context("File R/', path_quoted, '")', "\n\n",
                       contents)
    
    writeLines(text = enc2utf8(contents), 
               con = path, 
               useBytes = TRUE)
  }
  
  
  return(paths)
}

#' @export
roclet_clean.roclet_testthat <- function(x, base_path) {
  verify_testthat_used()
  
  testfiles <- dir(path = file.path(base_path, "tests", "testthat"), 
                   pattern = "^test-roxytest-.*\\.R$", 
                   full.names = TRUE)
  testfiles <- testfiles[!file.info(testfiles)$isdir]
  
  made_by_me <- vapply(testfiles, made_by_roxytest, logical(1))

  unlink(testfiles[made_by_me])
}

