# Adapted from roxygen2's
# https://github.com/klutometis/roxygen/blob/master/R/rd.R

#' Roclet: make testthat test-files.
#'
#' @family roclets
#' @description This roclet is the workhorse of roxytest, 
#' producing the testthat test files specified.
#' 
#' Generally you will not call this function directly
#' but will instead use roxygenise() specifying the testthat roclet
#' 
#' @seealso Other roclets:
#' \code{\link[roxygen2]{namespace_roclet}}, 
#' \code{\link[roxygen2]{rd_roclet}},
#' \code{\link[roxygen2]{vignette_roclet}}.
#' 
#' @export
testthat_roclet <- function() {
  return(roxygen2::roclet("testthat"))
}


#' @export
roclet_tags.roclet_testthat <- function(x) {
  list(
    tests = tag_tests
  )
}

#' @export
roclet_process.roclet_testthat <- function(x,
                                           blocks,
                                           env,
                                           base_path,
                                           global_options = list()) {
  
  testfiles <- list()
  
  for (block in blocks) {
    testthat <- block_to_testthat(block, 
                                  base_path = base_path, 
                                  env = env, 
                                  global_options = global_options)
    
    if (is.null(testthat$filename) || is.null(testthat$tests)) {
      next
    }
    
    
    testfiles[[testthat$filename]] <- c(testfiles[[testthat$filename]], 
                                        list(testthat))
  }
  
  ######################################
  
  paths <- names(testfiles)
  
  results <- lapply(seq_along(testfiles), function(i) {
    testfile <- testfiles[[i]]
    
    content <- lapply(testfile, function(x) {
      tests <- x$tests
      tests <- gsub("^\\s*(.*?)\\s*$", "\\1", tests)
      tests_indented <- paste0("  ", gsub("\n", "\n  ", tests, fixed = TRUE))
      tests_name <- paste0("Function ", 
                           roxygen2:::quote_if_needed(x$functionname), "()")
      
      paste0('test_that("', tests_name, '", {', "\n", 
             tests_indented, "\n",
             "})\n")
    })
    
    content <- paste0(content, collapse = "\n\n")
    
    path_quoted <- roxygen2:::quote_if_needed(paths[i])
    content <- paste0("# Generated by roxytest: Do not edit by hand!\n\n", 
                      'context("File R/', path_quoted, '")', "\n\n",
                      content)
    
    return(content)
  })
  
  names(results) <- paths
  
  return(results)
}

block_to_testthat <- function(block, base_path, env, global_options = list()) {
  testthat_file <- list()
  
  tests <- if (!is.null(block$tests)) {
    tests <- block$tests
  } else {
    NULL
  }
  
  testthat_file$tests <- tests
  
  filename <- basename(attr(block, "filename"))
  testthat_file$filename <- filename
  
  testthat_file$functionname <- attr(block, "object")$alias
  
  return(testthat_file)
}

#' @export
roclet_output.roclet_testthat <- function(x, results, base_path, ..., is_first = FALSE) {
  verify_testthat_used()
  
  roclet_clean.roclet_testthat(x, base_path)
  
  testthat_path <- normalizePath(file.path(base_path, "tests", "testthat"))
  
  paths <- names(results)
  
  for (i in seq_along(results)) {    
    path <- file.path(testthat_path, paste0("test-roxytest-", paths[i]))
    
    if (file.exists(path)) {
      warning(paste0("The file '", path, "' was not created by roxytest (wrong header), ", 
                     "and hence was not modified as planned. ",
                     "Please be sure that this is intended."))
      next
    }
    
    content <- results[[i]]
    
    writeLines(text = enc2utf8(content), 
               con = path, 
               useBytes = TRUE)
  }
  
  return(paths)
}

#' @export
roclet_clean.roclet_testthat <- function(x, base_path) {
  verify_testthat_used()
  
  testfiles <- dir(path = file.path(base_path, "tests", "testthat"), 
                   pattern = "^test-roxytest-.*\\.R$", 
                   full.names = TRUE)
  testfiles <- testfiles[!file.info(testfiles)$isdir]
  
  made_by_me <- vapply(testfiles, made_by_roxytest, logical(1))
  
  if (sum(!made_by_me) > 0) {
    warning(paste0("Clean-up: Some files in tests/testthat/ with the file name pattern ", 
                   "test-roxytest-*.R was not created by roxytest (missing header), ", 
                   "and hence was not removed. ",
                   "Please be sure that this is intended."))
  }
  
  unlink(testfiles[made_by_me])
}

